server:
  port: 8080

eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://3.7.2.2:8761/eureka
  

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            exposedHeaders: "*"
      routes:
        #Route Mapping
        - id: authentication-service
          uri: http://3.7.2.2:8095/
          predicates:
            - Path=/authentication/**
          filters:
            - RewritePath=/authentication(?<segment>/?.*), $\{segment}

            #Route Mapping
        - id: bookings-management
          uri: http://3.7.2.2:8087/
          predicates:
            - Path=/booking-Management/**
          filters:
            - RewritePath=/booking-Management(?<segment>/?.*), $\{segment}

        #Route Mapping
        - id: chat-service
          uri: http://3.7.2.2:8086/
          predicates:
            - Path=/chat/**
          filters:
            - RewritePath=/chat(?<segment>/?.*), $\{segment}

        #Route Mapping
        - id: email-service
          uri: http://3.7.2.2:8085/
          predicates:
            - Path=/email/**
          filters:
            - RewritePath=/email(?<segment>/?.*), $\{segment}


        #Route Mapping
        - id: payment
          uri: http://3.7.2.2:8084/
          predicates:
            - Path=/payment/**
          filters:
            - RewritePath=/payment(?<segment>/?.*), $\{segment}

        #Route Mapping
        - id: team-up
          uri: http://3.7.2.2:8082/
          predicates:
            - Path=/team/**
          filters:
            - RewritePath=/team(?<segment>/?.*), $\{segment}

        #Route Mapping
        - id: user-service
          uri: http://3.7.2.2:8081/
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user(?<segment>/?.*), $\{segment}

        #Route Mapping
        - id: config-server
          uri: http://3.7.2.2:8888/
          predicates:
            - Path=/config/**
          filters:
            - RewritePath=/config(?<segment>/?.*), $\{segment}


        #Route Mapping
        - id: product-webapp
          uri: http://3.7.2.2:3000/
          predicates:
            - Path=/**
          filters:
            - RewritePath=(?<segment>/?.*), $\{segment}


# spring:
#   cloud:
#     config:
#       uri: http://localhost:8888
#   application:
#     name: api-gateway
#   main:
#     web-application-type: reactive
# management:
#   security:
#     enabled: false
