server:
  port: 8086
spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: chat
  application:
    name: chat-service
  cloud:
    config:
      uri: http://localhost:8888
      import-check.enabled: false
management:
  security:
    enabled: false