server:
  port: 8087
spring:
  data:
    mongodb:
      host: 3.7.2.2
      port: 27017
      database: Bookings
  application:
    name: bookings-management

  rabbitmq:
    port: 5672
    host: 3.7.2.2
    username: guest
    password: guest
    
eureka:
  client:
    registerWithEureka: true
    fetchRegistry: true
    service-url:
      defaultZone: http://3.7.2.2:8761/eureka



# server:
#   port: 8087
# spring:
#   data:
#     mongodb:
#       host: localhost
#       port: 27017
#       database: Bookings
#   application:
#     name: bookings-management
#   cloud:
#     config:
#       uri: http://localhost:8888
#       import-check.enabled: false
# management:
#   security:
#     enabled: false
